CryptoViewer.MVC/ViewComponents/MainMenuViewComponent.cs
using CryptoViewer.MVC.Helpers;
using Microsoft.AspNetCore.Mvc;
using System;
using CryptoViewer.MVC.Models.Dto;
using System.Threading.Tasks;

namespace CryptoViewer.MVC.ViewComponents
{
    /// <summary>
    /// View component responsible for rendering the main menu based on user session.
    /// </summary>
    public class MainMenuViewComponent : ViewComponent
    {
        private readonly IApiHelper api;
        private readonly IWebCookie web;

        /// <summary>
        /// Initializes a new instance of the <see cref="MainMenuViewComponent"/> class.
        /// </summary>
        /// <param name="api">Instance of <see cref="IApiHelper"/> for API interactions.</param>
        /// <param name="web">Instance of <see cref="IWebCookie"/> for handling web cookies.</param>
        public MainMenuViewComponent(IApiHelper api, IWebCookie web)
        {
            this.api = api;
            this.web = web;
        }

        /// <summary>
        /// Asynchronous method invoked to render the view component.
        /// </summary>
        /// <returns>An asynchronous task that returns an <see cref="IViewComponentResult"/>.</returns>
        public async Task<IViewComponentResult> InvokeAsync()
        {
            // Get the session ID from the web cookie
            var session = web.Get("CustomSession");

            // If session does not exist, generate a new GUID and set it as the session ID cookie
            if (string.IsNullOrEmpty(session))
            {
                var guid = Guid.NewGuid();
                session = guid.ToString();
                web.AddSecure("CustomSession", session, 5); // Adding a secure cookie with 5 days expiration

                return View("Index", false); // Return the view with isLoggedIn = false
            }

            // Check if the session ID is logged in by calling an API
            var isLoggedIn = await api.PostAsync<IsLoggedInResponse>("api/DbSession/isLoggedInByGuid", new { sessionId = session });

            return View("Index", isLoggedIn.Result); // Return the view with the isLoggedIn status
        }
    }
}

CryptoViewer.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CryptoViewer.MVC</title>

    <link rel="stylesheet" href="~/css/NavBar/NavBar.css">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CryptoViewer.MVC.styles.css" asp-append-version="true" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/Images/analytics.png"/>
                </a>
                
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Tracker" asp-action="Tracker">Tracker's'</a>
                        </li>
                        
                        @await Component.InvokeAsync("MainMenu")
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

@*     <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Saityno paslaugų galutinis projektas<br />
        </div>
    </footer> *@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>